#!/bin/bash

## password/libs/bashlib.sh - sourced into every srvctl shell by load_libs.
## new_password: echoes one pronounceable Word-Word password generated by
## the Node implementation (get-password.js). The pure-bash equivalent is
## get_password in libs/get-password.sh. On node failure exif terminates
## the whole srvctl run with node's exit code; callers do not handle errors.

function new_password {

    local __result
    ## arguments are forwarded to get-password.js, which ignores them
    ## FIXME(v4): 2>&1 merges node stderr into the captured value; a
    ## non-fatal node warning would silently corrupt the credential.
    # shellcheck disable=SC2048
    # shellcheck disable=SC2086
    __result="$(/bin/node "$SC_INSTALL_DIR/modules/password/get-password.js" $* 2>&1)"
    ## FIXME(v4): "SSH-ERROR" is copy-pasted from an SSH lib; a node
    ## failure here is misreported as an SSH error.
    exif "SSH-ERROR cfg $* ($?) $__result"

    echo "$__result"
}
