#!/bin/bash

##
##   authlib — srvctl's entire permission model, used by ~60 call sites
##   across nearly all modules. Exit codes are conventions relied on by
##   callers: 44 = authorization failure, 32 = missing argument.
##   The bare word root_only / reseller_only within the first 20 lines of a
##   command file doubles as a visibility marker for help listings.
##

function root_only {
    if $SC_UID0
    then
        ## FIXME(v4): debug leftover — this echo puts "SC_UID0 true" on
        ## stdout of every root-only command, polluting captured output.
        ## Preserved: scripts may already expect the line.
        echo "SC_UID0 $SC_UID0"
        return 0
    else
        err "Authorization failure. (root_only)"
        exit 44
    fi
}

function reseller_only {
    if [[ "${#SC_USER}" == 1 ]] || $SC_UID0
    then
        return 0
    else
        err "Resellers only."
        exit 44
    fi
}

function argument {
    if [[ -z $ARG ]]
    then
        err "Argument $1 missing."
        exit 32
    fi
}

function authorize {
    if $SC_UID0
    then
        return
    else
        ## there should be several levels of users
        ## root - allowed everything for everyone
        ## reseller - allowed for his users
        ## user - allowed for himself
        ## guest - limited.
        ## FIXME(v4): stub — a non-root caller only gets this error message
        ## and then CONTINUES; authorize never denies anything.
        err "DEV (Authorization implementation not complete.)"
    fi
}

## non-root re-exec through sudo; sudoers entries generated by usersonhost
## target exactly "$SC_INSTALL_DIR/srvctl.sh *"
function sudomize {
    if ! $SC_UID0
    then
        debug "@sudomize"
        ## FIXME(v4): $SC_COMMAND_ARGUMENTS is passed as ONE word here and
        ## then re-split by run's unquoted expansion — the original argv
        ## boundaries are lost, so arguments containing spaces collapse.
        if run sudo "$SC_INSTALL_DIR/srvctl.sh" "$SC_COMMAND_ARGUMENTS"
        then
            exit
        else
            debug "Error $? in srvctl-sudo"
            ## FIXME(v4): 'exit $?' takes the exit status of debug (0), not
            ## of the failed sudo re-exec — failures are masked to exit 0.
            exit $?
        fi
    fi
}
