#!/bin/bash

##
##   authlib — srvctl's entire permission model, used by ~60 call sites
##   across nearly all modules. Exit codes are conventions relied on by
##   callers: 44 = authorization failure, 32 = missing argument.
##   The bare word root_only / reseller_only within the first 20 lines of a
##   command file doubles as a visibility marker for help listings.
##

function root_only {
    if $SC_UID0
    then
        return 0
    else
        err "Authorization failure. (root_only)"
        exit 44
    fi
}

function reseller_only {
    if [[ "${#SC_USER}" == 1 ]] || $SC_UID0
    then
        return 0
    else
        err "Resellers only."
        exit 44
    fi
}

## owner_only <type> <id> — resource-ownership guard (WP-E.2).
##
##   MUST be called BEFORE any state change (check-before-act): it either
##   returns (authorized) or exits. Policy:
##     - root (SC_UID0) may act on everything for everyone -> return 0.
##     - the resource owner, or (transitionally, until WP-F) its reseller,
##       escalates to root via sudomize -> the command re-runs as root and
##       passes the SC_UID0 check above.
##     - anyone else is denied (exit 44).
##
##   Replaces the per-command 'authorize + owner-check + [[ $SC_UID0 ]]'
##   pattern. Lives here (always-loaded srvctl authlib) so every module,
##   host- or VE-side, shares one guard.
function owner_only { # $1 type  $2 id
    $SC_UID0 && return 0

    local _owner _reseller
    _owner="$(get "$1" "$2" user)"
    _reseller="$(get "$1" "$2" reseller)"

    if [[ $SC_USER == "$_owner" ]] || [[ $SC_USER == "$_reseller" ]]
    then
        ## owner but not root: re-exec through sudo, then the whole command
        ## re-runs and hits the SC_UID0 fast-path above.
        sudomize
    fi

    ## reached only by a non-root, non-owner caller (the owner branch above
    ## exits via sudomize's re-exec).
    err "$SC_USER has no access to $2"
    exit 44
}

function argument {
    if [[ -z $ARG ]]
    then
        err "Argument $1 missing."
        exit 32
    fi
}

function authorize {
    if $SC_UID0
    then
        return
    else
        ## there should be several levels of users
        ## root - allowed everything for everyone
        ## reseller - allowed for his users
        ## user - allowed for himself
        ## guest - limited.
        ## FIXME(v4): stub — a non-root caller only gets this error message
        ## and then CONTINUES; authorize never denies anything.
        err "DEV (Authorization implementation not complete.)"
    fi
}

## non-root re-exec through sudo; sudoers entries generated by usersonhost
## target exactly "$SC_INSTALL_DIR/srvctl.sh *"
function sudomize {
    if ! $SC_UID0
    then
        debug "@sudomize"
        ## FIXME(v4): $SC_COMMAND_ARGUMENTS is passed as ONE word here and
        ## then re-split by run's unquoted expansion — the original argv
        ## boundaries are lost, so arguments containing spaces collapse.
        if run sudo "$SC_INSTALL_DIR/srvctl.sh" "$SC_COMMAND_ARGUMENTS"
        then
            exit
        else
            debug "Error $? in srvctl-sudo"
            ## FIXME(v4): 'exit $?' takes the exit status of debug (0), not
            ## of the failed sudo re-exec — failures are masked to exit 0.
            exit $?
        fi
    fi
}
