#!/bin/node

/*
 * modules/default/server.js — srvctl default page server.
 *
 * Catch-all HTTP backend, run as user nobody by default-server.service
 * (generated by hooks/update-install-host.sh). haproxy's default_backend
 * sends every request whose Host matches no hosted site to
 * localhost:1282; this daemon logs the request to the journal and always
 * answers HTTP 404 with the branded page /var/www/html/404.html
 * (generated by the branding module). Nothing else in the tree imports
 * or sources this file.
 */

var http = require('http');
var fs = require('fs');

// FIXME(v4): unguarded readFileSync — if /var/www/html/404.html is absent
// the process throws before listen(); with Restart=always and no
// RestartSec the unit lands in permanent 'failed' state and haproxy
// serves its raw 503 instead of the branded 404.
// FIXME(v4): html404 is an implicit global (no var/let/const); works only
// in sloppy mode, would ReferenceError under "use strict"/ESM.
html404 = fs.readFileSync('/var/www/html/404.html');

var server = http.createServer(function onRequest(req, res) {

    // Log one greppable line per request: host url user-agent x-forwarded-for
    console.log(req.headers.host, req.url, req.headers['user-agent'], req.headers['x-forwarded-for']);

    
    res.writeHead(404, {'Content-Type': 'text/html'});  
    res.write(html404);  
    res.end();

});
// FIXME(v4): listen(1282) binds all interfaces although the only
// legitimate client is haproxy on localhost; should bind 127.0.0.1.
server.listen(1282);
console.log("srvctl default-server started");
