#!/bin/bash

##
##   modules/firewalld/libs/firewalldlib.sh — the "open a port" API.
##
##   Sourced into the shell via load_libs when SC_USE_FIREWALLD=true.
##   Cross-module ABI: firewalld_add_service and
##   firewalld_offline_add_service are called from ~10 other modules
##   (codepad, ftp, perdition, postfix, gluster, named, nfs, openvpn,
##   sshpiperd, gui) and from shell code generated by
##   modules/datastore/lib.js — do not rename them or reorder their
##   arguments.
##

## firewalld_add_service <name> [proto] [port] [hint]
## Idempotently enable service <name> in the default zone of the live
## system. If <name> is a built-in firewalld service and no proto/port
## is given, it is added directly; otherwise a service definition is
## written to /etc/firewalld/services/<name>.xml first. <hint> defaults
## to $SC_USER and lands in the XML description.
function firewalld_add_service() { ## name proto port hint

    ## FIXME(v4): hidden side effect — every call from any module starts
    ## firewalld.service (bare systemctl, not via run, no enable).
    systemctl start firewalld.service

    local zone name proto port hint

    name="$1"
    proto="$2"
    port="$3"
    hint="$4"

    if ! [[ $hint ]]
    then
        hint="$SC_USER"
    fi

    zone=$(firewall-cmd --get-default-zone)

    if [[ "$(firewall-cmd --zone="$zone" --permanent --query-service="$name")" == yes ]]
    then
        ntc "firewalld: $name is enabled already."
        return
    fi

    if [[ -f /usr/lib/firewalld/services/$name.xml ]] && [[ -z $proto ]] && [[ -z $port ]]
    then
        msg "Service $name already defined in firewalld"
        run firewall-cmd --zone="$zone" --permanent --add-service="$name"
    else
        msg "Creating /etc/firewalld/services/$name.xml"

        ## FIXME(v4): for an unknown service name with empty proto/port this
        ## writes <port protocol="" port=""/> — an invalid service file that
        ## persists on disk and can make every later 'firewall-cmd --reload'
        ## error until removed by hand.
cat > "/etc/firewalld/services/$name.xml" << EOF
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>$name</short>
  <description>$name $proto $port (srvctl added for $hint)</description>
  <port protocol="$proto" port="$port"/>
</service>
EOF

        ## the intermediate reload is required so firewalld learns the new
        ## service definition before the permanent add
        run firewall-cmd --reload
        run firewall-cmd --zone="$zone" --permanent --add-service="$name"
    fi

    run firewall-cmd --reload

}

## firewalld_offline_add_service <name> [proto] [port]
## Same idea against a not-yet-booted rootfs: all queries and changes go
## through 'chroot $rootfs firewall-offline-cmd' (offline changes are
## inherently permanent, no reload needed). Must be called from a hook
## with rootfs_base in scope (see hooks/mkrootfs_fedora.sh).
function firewalld_offline_add_service() { ## name proto port ## must be called with a hook

    local zone rootfs name proto port

    ## rootfs_base comes from parent containers mkrootfslib: mkrootfs_fedora_base
    # shellcheck disable=SC2154
    rootfs="$rootfs_base"
    name="$1"
    proto="$2"
    port="$3"

    msg "firewalld_offline_add_service $rootfs $name $proto $port"
    zone=$(chroot "$rootfs" firewall-offline-cmd --get-default-zone)

    if [[ "$(chroot "$rootfs" firewall-offline-cmd --zone="$zone" --query-service="$name")" == yes ]]
    then
        ntc "firewalld-offline: $name is enabled already."
        return
    fi

    if [[ -f $rootfs/usr/lib/firewalld/services/$name.xml ]] && [[ -z $proto ]] && [[ -z $port ]]
    then
        msg "Service $name defined in firewalld"
        run chroot "$rootfs" firewall-offline-cmd --zone="$zone" --add-service="$name"
    else
        msg "Creating $rootfs/etc/firewalld/services/$name.xml"

cat > "$rootfs/etc/firewalld/services/$name.xml" << EOF
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>$name</short>
  <description>$name $proto $port (added by srvctl)</description>
  <port protocol="$proto" port="$port"/>
</service>
EOF

        run chroot "$rootfs" firewall-offline-cmd --zone="$zone" --add-service="$name"
    fi

}
