/*
 * srvctl letsencrypt module — apps/acme-server.js
 *
 * Minimal always-on responder for the ACME http-01 challenge. Runs as the
 * acme-server.service systemd unit (User=acme, generated by install_acme in
 * libs/letsencryptlib.sh) and listens on 0.0.0.0:1028. HAProxy forwards
 * port-80 requests whose path begins with /.well-known/acme-challenge/ to
 * 127.0.0.1:1028 (haproxy.js backend "letsencrypt"); certbot --webroot
 * writes the token files under /var/acme/.well-known/acme-challenge/ and
 * this server plays them back. Any other URL gets a plain-text
 * "INVALID URL" reply (always HTTP 200).
 *
 * The port number and the challenge path prefix are shared API with the
 * haproxy module — never change one without the other. Scheduled to be
 * replaced by the v4 DNS-01 wildcard redesign (G7).
 */

// Load modules to create a http server.
var http = require("http");
var fs = require('fs');

// Configure our HTTP server to respond with a file-read to all requests on the acme URL.
var http_server = http.createServer(function(req, res) {
    res.writeHead(200, {
        "Content-Type": "text/plain"
    });
    if (req.url.substring(0, 28) == "/.well-known/acme-challenge/" && req.url.length > 28) {

        var ch = req.url.substring(28);
        var file = '/var/acme/.well-known/acme-challenge/' + ch;

        // FIXME(v4): fs.R_OK is a long-deprecated alias of fs.constants.R_OK;
        // on Node versions where it is undefined, fs.access degrades to an
        // F_OK existence check, so an existing-but-unreadable file falls
        // through to readFile and answers "INVALID DATA" instead of the
        // intended "CANNOT READ" branch.
        fs.access(file, fs.R_OK, function(err) {
            if (!err) {
                fs.readFile(file, function(err, data) {
                    if (err) return res.end("INVALID DATA");
                    var content = data.toString();
                    console.log("CONTENT: " + content);
                    res.end(content);
                });
            } else {
                console.log("CANNOT READ: " + ch);
                res.end("CANNOT READ: " + ch);
            }

        });

    } else {
        res.end("INVALID URL: " + req.url);
        console.log("INVALID URL: " + req.url);
    }
});

http_server.listen(1028);
console.log('Started acme-server.js');
