## srvctl3 containerfarm

fs.file-max = 4194304
fs.inotify.max_queued_events = 2097152
fs.inotify.max_user_instances = 2097152
fs.inotify.max_user_watches = 4194304

#kernel.pid_max=4194304

## use minimum of swap
vm.swappiness = 1

## please note temporary bugfix at: https://srvctl-devel.d250.hu:9001/p/modules/containers/hooks/regenerate.sh